sudo: false
os:
  - linux

env:
  - CONDA_PY=3.8
  - CONDA_PY=3.7

services:
  - postgresql

addons:
  postgresql: "9.5"

before_install:
  # resizing became necessary due to the test database size, and variation
  # in travis instances w.r.t. ramfs where postgres runs out of
  - sudo mount -o remount,size=25% /var/ramfs
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda create --yes -n env_name python=$CONDA_PY
  - conda install --yes -n env_name --file ci/conda_requirements.txt
  - source activate env_name
  - pip install -r ci/pip_requirements.txt
  - make install

before_script:
  - python microsetta_private_api/LEGACY/build_db.py

script:
  - make lint
  - make test-cov

after_success:
  - coveralls
